module.exports = [
{
	ID: 1,
	title: "Homemade Blue Laser",
	date: "March 2015",
	description: "This was just a simple project for me to experiment with lasers. I bought a 2W laser diode and built it into a host with a laser driver and some rechargeable batteries. The laser is strong enough to light matches and burn paper. It's pretty cool.",
	url: "http://cjblocker.blogspot.com/2015/07/homemade-laser.html",
	right: true,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/blue_laser/_thumbnail.jpg"
},
{
	ID: 2,
	title: "Gameboy Calculator",
	date: "2008",
	description: "I made this \"Gameboy Calculator\" when I was in high school. I was in my freshmen pre-AP math class and well the course pace was a little slow for me. So I gutted a old calculator and rewired all the buttons of a Gameboy SP to it's buttons. I almost beat my Pokemon game in pre-AP Algebra II. It wasn't till my AP Calculus teacher had heard the rumors that I got caught senior year.",
	url: "http://cjblocker.blogspot.com/2011/06/introduction-of-sorts-and-gameboy.html",
	right: true,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/calculator/_thumbnail.jpg"
},
{
	ID: 3,
	title: "Mission in Cambodia",
	date: "2013",
	description: "I was a missionary for the Church of Jesus Christ of Latter-Day Saints in the country of Cambodia for two years. While a missionary, I learned the Cambodian language, taught about Christ and English on a daily basis, and served in a variety of leadership roles.",
	url: "http://www.missionsite.net/eldercameronblocker",
	right: false,
	xshift: 0,
	tags:["misc"],
	thumbnail:"img/projects/cambodia/_thumbnail.jpg"
},
{
	ID: 4,
	title: "Digi-Theremin",
	date: "November 6, 2015",
	description: "This was my team's project at the MLH hackUstate hackathon where we took 3rd place. We built a simple interface that using a Myo Armband and a brainwave detector could play the sounds of your thoughts in synthesized tones. I also took first in a web dev mini challenge.",
	url: "",
	right: true,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/digitheremin/_thumbnail.jpg"
},
{
	ID: 5,
	title: "Electric Skateboard",
	date: "2011",
	description: "I was given a broken electric scooter in high school because I apparently had a reputation for collecting junk. I fixed the power circuit and shaped my own longboard to build it into. The longboard also featured LED underlights that blinked in sync with my built in stereo system.",
	url: "http://cjblocker.blogspot.com/2011/09/electric-skateboard-early-stages.html",
	right: false,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/electric_skateboard/_thumbnail.jpg"
},
{
	ID: 6,
	title: "Holo-Video Monitor",
	date: "January 2015",
	description: "This is what I work on in BYU's ElectroHolography Lab. It's based off of MIT's Mark IV architecture. I design circuit boards, embedded software, and GPU algorithms for producing 3D holographic images with the potential of recreating all depth cues.",
	url: "",
	right: false,
	xshift: 0,
	tags:["research"],
	thumbnail:"img/projects/holomonitor/_thumbnail.jpg"
},
{
	ID: 7,
	title: "Plasma Speaker",
	date: "April 2011",
	description: "My high school physics teacher was showing us cool stuff on youtube when he showed us a plasma speaker that played music by modulating an electric arc. I decided I wanted to make one so I started researching them online and made one. I stole parts out of an old CRT television to make it. Kids at school thought it was pretty cool.",
	url: "http://cjblocker.blogspot.com/2011/07/plasma-speaker.html",
	right: true,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/plasma_speaker/_thumbnail.jpg"
},
{
	ID: 8,
	title: "Portable N64",
	date: "June 2010",
	description: "I took apart an old Nintendo64 and wired it up to run on batteries. It was great for long car rides like for out of town cross-country meets.",
	url: "http://cjblocker.blogspot.com/2011/06/compilation-of-miscellaneous.html",
	right: true,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/portable64/_thumbnail.jpg"
},
{
	ID: 9,
	title: "Self-Assembled 3D Printer",
	date: "March 2014",
	description: "I decided I wanted a 3D printer when I was in high school, so when I got to college I saved up my money by selling my plasma for a semester till I could afford to build my own. I looked in to designing my own from scratch but decided to use a kit for my first.",
	url: "http://cjblocker.blogspot.com/2014/06/building-3d-printer.html",
	right: true,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/printer3D/_thumbnail.jpg"
},
{
	ID: 10,
	title: "Radioshack Kit AM/FM Radio",
	date: "May 2002",
	description: "One of my first electronics projects in elementary school, well the first that actually worked. I remember taking apart a walkie-talkie (Stars Wars ones, they were) and trying to lengthen the microphone wire so I could embed it in my watch when I was like in Kindergarten. It didn't work. Now I know how electricity works and why the microphone had two wires.",
	url: "",
	right: true,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/radio_kit/_thumbnail.jpg"
},
// {
// 	ID: 11,
// 	title: "AVR RTOS",
// 	date: "November 2015",
// 	description: "We built a real time operating system in class for the x86. I wanted one for the Arduino.",
// 	url: "",
// 	right: true,
//	xshift: 0,
// 	tags:["school"],
// 	thumbnail:"img/projects/rtos/_thumbnail.jpg"
// },
{
	ID: 12,
	title: "Homemade LED/Laser Diode",
	date: "November 18, 2015",
	description: "This is from a grad class (ECEn 555) I took at BYU. We made LEDs and Lasers out of GaAs in BYU's Cleanroom. Our LED was red and our laser emitted in the infrared. We also made solar cells and photodiodes in silicon.",
	url: "",
	right: true,
	xshift: 170,
	tags:["school"],
	thumbnail:"img/projects/semiconductor_led/_thumbnail.jpg"
},
{
	ID: 13,
	title: "Stereo",
	date: "June 2014",
	description: "This was the lab project for one of the entry level classes for EE's at BYU. It's a simple stereo with treble/bass control and balancing in addition to the usual volume and mic mixer.",
	url: "",
	right: true,
	xshift: 100,
	tags:["school"],
	thumbnail:"img/projects/stereo/_thumbnail.jpg"
},
{
	ID: 14,
	title: "Microfluidic Devices Laser Driver",
	date: "December 2015",
	description: "This was for my senior project. I worked on a circuit for driving a laser that we used to detect proteins flowing down a microfluidic channel.",
	url: "",
	right: false,
	xshift: 0,
	tags:["school"],
	thumbnail:"img/projects/ufluidic/_thumbnail.jpg"
},
{
	ID: 15,
	title: "Wearable Computing",
	date: "July 2014",
	description: "I built a GoogleGlass like HMD the clipped onto my glasses. It connected through a wire down to a Raspberry Pi that provided a video feed. I added voice controls through the google voice API and designed a hand periphereal for controlling it as well.",
	url: "http://cjblocker.blogspot.com/2014/09/wearable-computing.html",
	right: false,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/wearable_computer/_thumbnail.jpg"
},
{
	ID: 16,
	title: "Light Up Wiimotes",
	date: "2006",
	description: "An early project that really got me into soldering. I added LED to my Wiimotes. I was already very comfortable taking things apart and there were guides online that helped me figure out how to do the rest. I destroyed my Dad's soldering iron tip learing to solder on that thing.",
	url: "http://cjblocker.blogspot.com/2011/06/compilation-of-miscellaneous.html",
	right: false,
	xshift: 0,
	tags:[],
	thumbnail:"img/projects/wiimote/_thumbnail.jpg"
},
{
	ID: 17,
	title: "RedBull PDX Flugtag: Team McFly",
	date: "August 1, 2015",
	description: "While interning at Intel, I helped build an aircraft to compete in RedBull's Flugtag competition in Portland. We had a Back to the Future theme and I played Marty McFly as I piloted our homemade aircraft off a 30ft drop into a river.",
	url: "http://thedarkroomnerd.com/2015/10/01/redbull-portland-flugtag-2015-team-mcfly/",
	right: false,
	xshift: 100,
	tags:["misc"],
	thumbnail:"img/projects/flugtag/_thumbnail.jpg"
},
]